from enum import IntEnum

class ProofLevel(IntEnum):
    OBSERVATION=0
    DETERMINISTIC_REPLAY=1
    CRYPTOGRAPHIC_INTEGRITY=2
    MERKLE_STATE=3
    ATTESTATION=4
    ZK_EXECUTION=5
    FORMAL_VERIFICATION=6
